#!/bin/bash
# Scaffolds a complete API integration from templates

set -e

if [ -z "$1" ] || [ -z "$2" ]; then
    echo "Usage: $0 SOURCE_NAME BASE_URL [RATE_LIMIT]"
    echo ""
    echo "Arguments:"
    echo "  SOURCE_NAME   Name of the job source (e.g., AngelList, Remotive)"
    echo "  BASE_URL      API base URL (e.g., https://api.angel.co/1)"
    echo "  RATE_LIMIT    Optional: requests per hour (default: 100)"
    echo ""
    echo "Example:"
    echo "  $0 AngelList https://api.angel.co/1 200"
    exit 1
fi

SOURCE_NAME="$1"
BASE_URL="$2"
RATE_LIMIT="${3:-100}"

# Convert to different cases
PASCAL_NAME="$(echo "$SOURCE_NAME" | sed -E 's/(^|[^a-zA-Z0-9])([a-z])/\U\2/g' | sed 's/[^a-zA-Z0-9]//g')"
LOWER_NAME="$(echo "$SOURCE_NAME" | tr '[:upper:]' '[:lower:]' | sed 's/[^a-z0-9]//g')"

PROJECT_ROOT="${PROJECT_ROOT:-/Users/jasonl/Desktop/manifest and match  v7/V7 build files/v7codebase/Manifest_and_Match_V7_Working code base: instruction files /upgrade/v_7_uppgrade}"
SOURCES_DIR="$PROJECT_ROOT/Packages/V7JobSources/Sources/V7JobSources"

if [ ! -d "$SOURCES_DIR" ]; then
    echo "❌ Sources directory not found: $SOURCES_DIR"
    echo "💡 Set PROJECT_ROOT environment variable to your project path"
    exit 1
fi

echo "🏗️  Scaffolding $PASCAL_NAME API Integration"
echo "=" * 80
echo "Source Name:    $SOURCE_NAME"
echo "Pascal Case:    $PASCAL_NAME"
echo "Lower Case:     $LOWER_NAME"
echo "Base URL:       $BASE_URL"
echo "Rate Limit:     $RATE_LIMIT req/hour"
echo "Output Dir:     $SOURCES_DIR"
echo ""

# Create main job source file
echo "📝 Creating ${PASCAL_NAME}JobSource.swift..."
cat > "$SOURCES_DIR/${PASCAL_NAME}JobSource.swift" <<EOF
// Generated by API Integration Builder
// Source: $SOURCE_NAME
// Base URL: $BASE_URL

import Foundation
import V7Thompson
import V7Core

/// $SOURCE_NAME job board integration
/// Documentation: [Add API docs URL]
/// Rate Limit: $RATE_LIMIT requests/hour
/// Authentication: [TODO: Specify auth type]
@MainActor
public final class ${PASCAL_NAME}JobSource: JobSourceProtocol {
    // MARK: - Properties

    private let apiClient: ${PASCAL_NAME}APIClient
    private let adapter: ${PASCAL_NAME}Adapter
    private let cache: JobCache

    public let sourceIdentifier: String = "$LOWER_NAME"
    public let displayName: String = "$SOURCE_NAME"

    // MARK: - Initialization

    public init(
        apiClient: ${PASCAL_NAME}APIClient = ${PASCAL_NAME}APIClient(),
        adapter: ${PASCAL_NAME}Adapter = ${PASCAL_NAME}Adapter(),
        cache: JobCache = JobCache(ttl: 300)
    ) {
        self.apiClient = apiClient
        self.adapter = adapter
        self.cache = cache
    }

    // MARK: - Public Methods

    public func fetchJobs() async throws -> [V7Thompson.Job] {
        // Check cache first
        if let cached = await cache.getJobs(for: sourceIdentifier) {
            print("💾 \(displayName): Using cached jobs (\(cached.count) jobs)")
            return cached
        }

        // Fetch from API
        print("📡 \(displayName): Fetching from API...")
        let apiJobs = try await apiClient.fetchJobs()

        // Adapt to Job model
        let jobs = apiJobs.compactMap { adapter.adapt(\$0) }

        // Cache results
        await cache.setJobs(jobs, for: sourceIdentifier)

        print("✅ \(displayName): Fetched \(jobs.count) jobs")
        return jobs
    }

    public func fetchJob(id: String) async throws -> V7Thompson.Job? {
        // Try cache first
        if let jobs = await cache.getJobs(for: sourceIdentifier),
           let job = jobs.first(where: { \$0.id.uuidString == id }) {
            return job
        }

        // Fetch specific job from API
        guard let apiJob = try await apiClient.fetchJob(id: id) else {
            return nil
        }

        return adapter.adapt(apiJob)
    }

    public func clearCache() async {
        await cache.clear(for: sourceIdentifier)
    }
}
EOF

# Create API client
echo "📝 Creating ${PASCAL_NAME}APIClient.swift..."
cat > "$SOURCES_DIR/${PASCAL_NAME}APIClient.swift" <<EOF
// Generated by API Integration Builder
// Source: $SOURCE_NAME

import Foundation

/// API client for $SOURCE_NAME
/// Handles all network communication with proper error handling
actor ${PASCAL_NAME}APIClient {
    // MARK: - Configuration

    private let baseURL = "$BASE_URL"
    private let rateLimiter = RateLimiter(
        maxRequests: $RATE_LIMIT,
        perTimeInterval: 3600  // 1 hour
    )
    private let circuitBreaker = CircuitBreaker(
        failureThreshold: 3,
        recoveryTimeout: 60  // 1 minute
    )
    private let session: URLSession

    // MARK: - Initialization

    init(session: URLSession = .shared) {
        self.session = session
    }

    // MARK: - Public Methods

    func fetchJobs(limit: Int = 50) async throws -> [${PASCAL_NAME}Job] {
        // Check circuit breaker
        try await circuitBreaker.checkState()

        // Check rate limit
        try await rateLimiter.checkLimit()

        // TODO: Build request URL with query parameters
        guard let url = URL(string: "\(baseURL)/jobs?limit=\(limit)") else {
            throw APIError.invalidURL
        }

        var request = URLRequest(url: url)
        request.httpMethod = "GET"
        request.timeoutInterval = 10
        request.setValue("application/json", forHTTPHeaderField: "Accept")
        request.setValue("ManifestAndMatchV7/1.0", forHTTPHeaderField: "User-Agent")

        // TODO: Add authentication headers if needed
        // request.setValue("Bearer YOUR_API_KEY", forHTTPHeaderField: "Authorization")

        // Perform request with retry logic
        let (data, urlResponse) = try await performRequestWithRetry(request)

        guard let httpResponse = urlResponse as? HTTPURLResponse else {
            throw APIError.invalidResponse
        }

        guard httpResponse.statusCode == 200 else {
            throw APIError.httpError(httpResponse.statusCode)
        }

        // Record success
        await rateLimiter.recordRequest()
        await circuitBreaker.recordSuccess()

        // TODO: Parse response - update structure to match API
        let decoder = JSONDecoder()
        decoder.keyDecodingStrategy = .convertFromSnakeCase
        let response = try decoder.decode(${PASCAL_NAME}APIResponse.self, from: data)

        return response.jobs
    }

    func fetchJob(id: String) async throws -> ${PASCAL_NAME}Job? {
        try await circuitBreaker.checkState()
        try await rateLimiter.checkLimit()

        // TODO: Implement single job fetch
        let url = URL(string: "\(baseURL)/jobs/\(id)")!
        var request = URLRequest(url: url)
        request.httpMethod = "GET"
        request.timeoutInterval = 10

        do {
            let (data, urlResponse) = try await session.data(for: request)

            guard let httpResponse = urlResponse as? HTTPURLResponse else {
                throw APIError.invalidResponse
            }

            if httpResponse.statusCode == 404 {
                return nil  // Job not found
            }

            guard httpResponse.statusCode == 200 else {
                throw APIError.httpError(httpResponse.statusCode)
            }

            await rateLimiter.recordRequest()
            await circuitBreaker.recordSuccess()

            let decoder = JSONDecoder()
            decoder.keyDecodingStrategy = .convertFromSnakeCase
            let job = try decoder.decode(${PASCAL_NAME}Job.self, from: data)
            return job

        } catch {
            await circuitBreaker.recordFailure()
            throw error
        }
    }

    // MARK: - Private Methods

    private func performRequestWithRetry(
        _ request: URLRequest,
        maxRetries: Int = 3
    ) async throws -> (Data, URLResponse) {
        var lastError: Error?
        var retryDelay: TimeInterval = 1.0

        for attempt in 0..<maxRetries {
            do {
                let (data, response) = try await session.data(for: request)

                guard let httpResponse = response as? HTTPURLResponse else {
                    throw APIError.invalidResponse
                }

                // Handle rate limiting
                if httpResponse.statusCode == 429 {
                    let retryAfter = httpResponse.value(forHTTPHeaderField: "Retry-After")
                    let waitTime = TimeInterval(retryAfter ?? "60") ?? 60
                    print("⏸️  Rate limited, waiting \(waitTime)s...")
                    try await Task.sleep(nanoseconds: UInt64(waitTime * 1_000_000_000))
                    continue
                }

                // Retry server errors
                if httpResponse.statusCode >= 500 {
                    throw APIError.serverError(httpResponse.statusCode)
                }

                return (data, response)

            } catch {
                lastError = error

                if attempt < maxRetries - 1 {
                    print("⚠️  Attempt \(attempt + 1)/\(maxRetries) failed, retrying in \(retryDelay)s...")
                    try await Task.sleep(nanoseconds: UInt64(retryDelay * 1_000_000_000))
                    retryDelay *= 2.0  // Exponential backoff
                    retryDelay += Double.random(in: 0...(retryDelay * 0.25))  // Jitter
                }
            }
        }

        await circuitBreaker.recordFailure()
        throw lastError ?? APIError.maxRetriesExceeded
    }
}

// MARK: - API Models

// TODO: Update these structures to match actual API response
struct ${PASCAL_NAME}APIResponse: Codable {
    let jobs: [${PASCAL_NAME}Job]
}

struct ${PASCAL_NAME}Job: Codable, Identifiable {
    let id: String
    let title: String?
    let company: String?
    let location: String?
    let description: String?
    let salary: String?
    let url: String?
    let postedDate: String?
    let skills: [String]?

    // TODO: Add custom CodingKeys if API uses different field names
}
EOF

# Create adapter
echo "📝 Creating ${PASCAL_NAME}Adapter.swift..."
cat > "$SOURCES_DIR/${PASCAL_NAME}Adapter.swift" <<EOF
// Generated by API Integration Builder
// Source: $SOURCE_NAME

import Foundation
import V7Thompson

/// Adapts $SOURCE_NAME API responses to V7Thompson.Job model
struct ${PASCAL_NAME}Adapter {
    private let skillsExtractor = SkillsExtractor()

    func adapt(_ apiJob: ${PASCAL_NAME}Job) -> V7Thompson.Job? {
        // Validate required fields
        guard let title = apiJob.title, !title.isEmpty else {
            print("⚠️  [$SOURCE_NAME] Skipping job with empty title")
            return nil
        }

        guard let company = apiJob.company, !company.isEmpty else {
            print("⚠️  [$SOURCE_NAME] Skipping job with missing company")
            return nil
        }

        // Build Job
        return V7Thompson.Job(
            id: UUID(),  // Generate fresh UUID
            title: title,
            company: company,
            location: apiJob.location ?? "Remote",
            description: apiJob.description,
            salary: apiJob.salary,
            skills: extractSkills(from: apiJob),
            url: parseURL(apiJob.url),
            remote: apiJob.location?.localizedCaseInsensitiveContains("remote") ?? false,
            postedDate: parseDate(apiJob.postedDate),
            source: "$SOURCE_NAME",
            applicationUrl: parseURL(apiJob.url),
            fetchedAt: Date(),
            sourceIdentifier: "$LOWER_NAME"
        )
    }

    // MARK: - Helper Methods

    private func extractSkills(from apiJob: ${PASCAL_NAME}Job) -> [String] {
        var skills: [String] = []

        // Use explicit skills if available
        if let apiSkills = apiJob.skills {
            skills.append(contentsOf: apiSkills)
        }

        // Extract from description
        if let description = apiJob.description {
            let extracted = skillsExtractor.extract(from: description)
            skills.append(contentsOf: extracted)
        }

        // Deduplicate and normalize
        let unique = Set(skills.map { \$0.trimmingCharacters(in: .whitespaces).capitalized })

        // Filter generics
        let filtered = unique.filter { !isGenericSkill(\$0) }

        return Array(filtered.prefix(10))
    }

    private func isGenericSkill(_ skill: String) -> Bool {
        let generic = ["Teamwork", "Communication", "Leadership", "Problem Solving"]
        return generic.contains(skill)
    }

    private func parseURL(_ urlString: String?) -> URL? {
        guard let urlString = urlString, !urlString.isEmpty else {
            return nil
        }
        return URL(string: urlString)
    }

    private func parseDate(_ dateString: String?) -> Date? {
        guard let dateString = dateString else { return nil }

        // TODO: Adjust date format to match API
        let formatter = ISO8601DateFormatter()
        return formatter.date(from: dateString)
    }
}
EOF

echo ""
echo "=" * 80
echo "🎉 Integration scaffolded successfully!"
echo "=" * 80
echo ""
echo "📂 Created files:"
echo "  • ${PASCAL_NAME}JobSource.swift"
echo "  • ${PASCAL_NAME}APIClient.swift"
echo "  • ${PASCAL_NAME}Adapter.swift"
echo ""
echo "📝 Next steps:"
echo ""
echo "1. Review API documentation for $SOURCE_NAME"
echo "   - Identify correct endpoints"
echo "   - Note authentication requirements"
echo "   - Check rate limits"
echo ""
echo "2. Update ${PASCAL_NAME}APIClient.swift:"
echo "   - Fix API endpoint URLs"
echo "   - Add authentication headers"
echo "   - Update response model (${PASCAL_NAME}Job)"
echo ""
echo "3. Update ${PASCAL_NAME}Adapter.swift:"
echo "   - Verify field mappings"
echo "   - Adjust date parsing"
echo "   - Test skills extraction"
echo ""
echo "4. Test the integration:"
echo "   swift test --filter ${PASCAL_NAME}Tests"
echo ""
echo "5. Validate data quality:"
echo "   ./scripts/validate_job_structure.sh $LOWER_NAME 20"
echo ""
echo "6. Add to job source registry"
echo ""
echo "💡 Tip: Search for TODO comments in generated files"
